import { DurableObject } from "cloudflare:workers";

export type UsageDecision =
  | {
      allowed: true;
      remaining: number;
      dailyLimit: number;
    }
  | {
      allowed: false;
      remaining: number;
      dailyLimit: number;
      retryAfterSeconds?: number;
      reason: "daily" | "burst" | "unauthorized";
    };

/**
 * One strongly-consistent usage counter per Vichar installation.
 *
 * The object is keyed by the opaque Vichar API key generated by the extension.
 * It stores only counters and UTC time buckets; no tweet text or user profile
 * data is stored here.
 */
export class VicharUsage extends DurableObject {
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);

    ctx.blockConcurrencyWhile(async () => {
      this.ctx.storage.sql.exec(`
        CREATE TABLE IF NOT EXISTS usage (
          id INTEGER PRIMARY KEY CHECK (id = 1),
          day TEXT NOT NULL,
          day_count INTEGER NOT NULL DEFAULT 0,
          minute INTEGER NOT NULL,
          minute_count INTEGER NOT NULL DEFAULT 0
        )
      `);
    });
  }

  async check(
    nowMs: number,
    dailyLimit: number,
    burstLimit: number,
  ): Promise<UsageDecision> {
    const now = new Date(nowMs);
    const day = now.toISOString().slice(0, 10);
    const minute = Math.floor(nowMs / 60_000);

    const row = this.ctx.storage.sql
      .exec<{
        day: string;
        day_count: number;
        minute: number;
        minute_count: number;
      }>("SELECT day, day_count, minute, minute_count FROM usage WHERE id = 1")
      .toArray()[0];

    let dayCount = row?.day_count ?? 0;
    let minuteCount = row?.minute_count ?? 0;

    if (!row || row.day !== day) {
      dayCount = 0;
    }
    if (!row || row.minute !== minute) {
      minuteCount = 0;
    }

    if (dayCount >= dailyLimit) {
      return {
        allowed: false,
        remaining: 0,
        dailyLimit,
        retryAfterSeconds: secondsUntilNextUtcDay(nowMs),
        reason: "daily",
      };
    }

    if (minuteCount >= burstLimit) {
      return {
        allowed: false,
        remaining: Math.max(0, dailyLimit - dayCount),
        dailyLimit,
        retryAfterSeconds: secondsUntilNextMinute(nowMs),
        reason: "burst",
      };
    }

    dayCount += 1;
    minuteCount += 1;

    this.ctx.storage.sql.exec(
      `
        INSERT INTO usage (id, day, day_count, minute, minute_count)
        VALUES (1, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
          day = excluded.day,
          day_count = excluded.day_count,
          minute = excluded.minute,
          minute_count = excluded.minute_count
      `,
      day,
      dayCount,
      minute,
      minuteCount,
    );

    return {
      allowed: true,
      remaining: Math.max(0, dailyLimit - dayCount),
      dailyLimit,
    };
  }
}

function secondsUntilNextMinute(nowMs: number): number {
  return Math.max(1, Math.ceil((60_000 - (nowMs % 60_000)) / 1000));
}

function secondsUntilNextUtcDay(nowMs: number): number {
  const now = new Date(nowMs);
  const next = Date.UTC(
    now.getUTCFullYear(),
    now.getUTCMonth(),
    now.getUTCDate() + 1,
  );
  return Math.max(1, Math.ceil((next - nowMs) / 1000));
}
